import React, { Component } from 'react';
import Land from './Land.js';

class LandTiles extends Component {
  constructor(props) {
    super(props);
    let self = this;
    this.state = {
    }
  }

  render() {
  let self = this;
  return (
    <div>

{/* England */}
      <Land
        src="http://imgur.com/HOM3XYY"
        class="London"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/cmtZ64i"
        class="Wales"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/gAneh9I"
        class="York"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/mBtpoUn"
        class="Edinburgh"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/ZDCpX2O"
        class="Clyde"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/rikd5cu"
        class="Liverpool"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/Ubw82Yu"
        class="Ireland"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

{/* Germany */}
      <Land
        src="http://imgur.com/pkAGRda"
        class="Berlin"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/EIK4sK9"
        class="Kiel"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/fkNBPGk"
        class="Ruhr"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/G5fJC56"
        class="Munich"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/nZcE2vL"
        class="Silesia"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/EeoFSgh"
        class="Prussia"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

{/* France */}
      <Land
        src="http://imgur.com/hfuPaS2"
        class="Brest"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/Yzzw4Pw"
        class="Burgundy"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/lVObu1M"
        class="Gascony"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/esw58Kg"
        class="Marseilles"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/ju4CZn9"
        class="Paris"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/VPrnX4e"
        class="Picardy"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

{/* Italy */}
      <Land
        src="http://imgur.com/mipwq9s"
        class="Apulia"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/rQ1vXCJ"
        class="Naples"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/BWQQ24b"
        class="Piemonte"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/9aVaLZQ"
        class="Rome"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/mcP2ZAM"
        class="Tuscany"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/U0Xg6Yl"
        class="Venice"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

{/* Austria */}
      <Land
        src="http://imgur.com/qYw5wGi"
        class="Bohemia"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/7m7iXK3"
        class="Budapest"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/TyuqzCr"
        class="Galicia"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/f9JWHfp"
        class="Trieste"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/wCVEhVT"
        class="Tyrolia"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/7enOk7w"
        class="Vienna"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

{/* Russia */}
      <Land
        src="http://imgur.com/e8JPUD9"
        class="Finland"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/QB1Cgqv"
        class="Livonia"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/wOi3tDj"
        class="Moscow"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/lMc99NQ"
        class="Ukraine"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/WXpnqF7"
        class="Warsaw"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/N0WTz6f"
        class="StPetersburg"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/rLMOhEj"
        class="Sevastopol"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

{/* Ottomans */}
      <Land
        src="http://imgur.com/hFgOrwO"
        class="Ankara"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/Hfpt5Pu"
        class="Armenia"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/pagAyMp"
        class="Constantinople"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/yutrrED"
        class="Smyrna"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/RPWmhOS"
        class="Syria"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

{/* Neutral */}

      <Land
        src="http://imgur.com/FkxdHVy"
        class="Albania"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/HxQZrMp"
        class="Belgium"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/INrLmUh"
        class="Bulgaria"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/I4hg7CP"
        class="Denmark"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/zTqYXm2"
        class="Greece"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/JU8tm5p"
        class="Holland"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/jX3l2O7"
        class="Iceland"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/7kQ3itz"
        class="NorthAfrica"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/34f7cdo"
        class="Norway"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/D1Y8iJ2"
        class="Portugal"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/qxvFPrU"
        class="Romania"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/yEgs1L0"
        class="Serbia"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/5cJLvc3"
        class="Spain"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/5QnkPdq"
        class="Sweden"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

      <Land
        src="http://imgur.com/TZPADte"
        class="Tunisia"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
      />

{/*Alphabetical Order with old halfsize src files

          <Land
            src="http://imgur.com/5cJLvc3"
            class="Spain"
            england={self.props.england}
            germany={self.props.germany}
            france={self.props.france}
            italy={self.props.italy}
            austria={self.props.austria}
            russia={self.props.russia}
            ottomans={self.props.ottomans}
          />

          <Land
            src="http://imgur.com/5QnkPdq"
            class="Sweden"
            england={self.props.england}
            germany={self.props.germany}
            france={self.props.france}
            italy={self.props.italy}
            austria={self.props.austria}
            russia={self.props.russia}
            ottomans={self.props.ottomans}
          />

          <Land
            src="http://imgur.com/TZPADte"
            class="Tunisia"
            england={self.props.england}
            germany={self.props.germany}
            france={self.props.france}
            italy={self.props.italy}
            austria={self.props.austria}
            russia={self.props.russia}
            ottomans={self.props.ottomans}
          />


      <Land
        src="http://imgur.com/UD2uk7t"
        class="Albania"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={0}
      />

      <Land
        src="http://imgur.com/PhYYycc"
        class="Ankara"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={1}
      />

      <Land
        src="http://imgur.com/82Jx00C"
        class="Apulia"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={2}
      />

      <Land
        src="http://imgur.com/O6QSZSp"
        class="Armenia"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={3}
      />

      <Land
        src="http://imgur.com/N4tVFt7"
        class="Belgium"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={4}
      />

      <Land
        src="http://imgur.com/3fVNa5x"
        class="Berlin"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={5}
      />

      <Land
        src="http://imgur.com/Z21VnQv"
        class="Bohemia"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={6}
      />

      <Land
        src="http://imgur.com/stQHfGR"
        class="Brest"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={7}
      />

      <Land
        src="http://imgur.com/yKHFBz3"
        class="Budapest"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={8}
      />

      <Land
        src="http://imgur.com/uiWBbB1"
        class="Bulgaria"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={9}
      />

      <Land
        src="http://imgur.com/2v3Gxan"
        class="Burgundy"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={10}
      />


      <Land
        src="http://imgur.com/xDXflF0"
        class="Clyde"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={11}
      />


      <Land
        src="http://imgur.com/Sp7FvbL"
        class="Constantinople"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={12}
      />


      <Land
        src="http://imgur.com/jQ9CPbS"
        class="Denmark"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={13}
      />

      <Land
        src="http://imgur.com/QI38Xvv"
        class="Edinburgh"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={14}
      />

      <Land
        src="http://imgur.com/Olq31Ea"
        class="Finland"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={15}
      />


      <Land
        src="http://imgur.com/YwGIydO"
        class="Galicia"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={16}
      />

      <Land
        src="http://imgur.com/eWcglBh"
        class="Gascony"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={17}
      />


      <Land
        src="http://imgur.com/shoFfVl"
        class="Greece"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={18}
      />


      <Land
        src="http://imgur.com/drUHzO0"
        class="Holland"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={19}
      />


      <Land
        src="http://imgur.com/mixad5l"
        class="Iceland"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={20}
      />


      <Land
        src="http://imgur.com/X1GD7xn"
        src2="http://imgur.com/8T9Xetf"
        class="Ireland"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={21}
      />

      <Land
        src="http://imgur.com/dPGH421"
        class="Kiel"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={22}
      />

      <Land
        src="http://imgur.com/mfWVmK7"
        class="Liverpool"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={23}
      />

      <Land
        src="http://imgur.com/2o3JRdK"
        class="Livonia"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={24}
      />

      <Land
        src="http://imgur.com/MxgSNJJ"
        src2=""
        class="London"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={25}
      />

      <Land
        src="http://imgur.com/zBKWCiB"
        class="Marseilles"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={26}
      />

      <Land
        src="http://imgur.com/QCVzYjn"
        class="Moscow"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={27}
      />

      <Land
        src="http://imgur.com/y4kAnDj"
        class="Munich"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={1}
        spritePosition={28}
      />

      <Land
        src="http://imgur.com/X0tHOAH"
        class="Naples"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={0}
      />

      <Land
        src="http://imgur.com/eGEXqYD"
        class="NorthAfrica"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={1}
      />

      <Land
        src="http://imgur.com/bXcSIjR"
        class="Norway"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={2}
      />

      <Land
        src="http://imgur.com/9Zy7fez"
        class="Paris"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={3}
      />

      <Land
        src="http://imgur.com/pgwLtCE"
        class="Picardy"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={4}
      />

      <Land
        src="http://imgur.com/7SY9rqt"
        class="Piemonte"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={5}
      />

      <Land
        src="http://imgur.com/nBngNdr"
        class="Portugal"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={6}
      />

      <Land
        src="http://imgur.com/anq2Uht"
        class="Prussia"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={7}
      />

      <Land
        src="http://imgur.com/VN5YFgk"
        class="Romania"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={8}
      />

      <Land
        src="http://imgur.com/K8gkoAp"
        class="Rome"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={9}
      />

      <Land
        src="http://imgur.com/JgyYUZZ"
        class="Ruhr"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={10}
      />

      <Land
        src="http://imgur.com/FSzuJ4g"
        class="Serbia"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={11}
      />

      <Land
        src="http://imgur.com/McgL8CK"
        class="Silesia"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={12}
      />

      <Land
        src="http://imgur.com/Nl9M0xU"
        class="Smyrna"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={13}
      />

      <Land
        src="http://imgur.com/BzXmdpw"
        class="Spain"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={14}
      />

      <Land
        src="http://imgur.com/lXrhaez"
        class="Sevastopol"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={15}
      />

      <Land
        src="http://imgur.com/dcBQ6tk"
        class="StPetersburg"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={16}
      />

      <Land
        src="http://imgur.com/6JajKTB"
        class="Sweden"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={17}
      />

      <Land
        src="http://imgur.com/4RQ8B1z"
        class="Syria"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={18}
      />

      <Land
        src="http://imgur.com/q6i9yXJ"
        class="Trieste"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={19}
      />

      <Land
        src="http://imgur.com/Shmmiv8"
        class="Tunisia"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={20}
      />

      <Land
        src="http://imgur.com/mBRxIBj"
        class="Tuscany"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={21}
      />

      <Land
        src="http://imgur.com/RJVzxFu"
        class="Tyrolia"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={22}
      />

      <Land
        src="http://imgur.com/ElSapqD"
        class="Ukraine"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={23}
      />

      <Land
        src="http://imgur.com/xQP0ch3"
        class="Venice"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={24}
      />

      <Land
        src="http://imgur.com/C5GKfXY"
        class="Vienna"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={25}
      />

      <Land
        src="http://imgur.com/4Xwt3bH"
        class="Wales"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={26}
      />

      <Land
        src="http://imgur.com/r81lB9Y"
        class="Warsaw"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={27}
      />

      <Land
        src="http://imgur.com/7scBlPF"
        class="York"
        england={self.props.england}
        germany={self.props.germany}
        france={self.props.france}
        italy={self.props.italy}
        austria={self.props.austria}
        russia={self.props.russia}
        ottomans={self.props.ottomans}
        latestChange={self.props.latestChange}
        spriteSheet={2}
        spritePosition={28}
      />
*/}

    </div>
    )
  }
}

export default LandTiles;
